CREATE DATABASE IF NOT EXISTS db_task5;
USE db_task5;

CREATE TABLE IF NOT EXISTS tbl_users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    status TINYINT DEFAULT 0
);
